spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pcm-web?autoReconnect=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    validation-query: select 1
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    time-between-eviction-runs-millis: 1800000
    num-tests-per-eviction-run: 3
    min-evictable-idle-time-millis: 1800000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: validate
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy