server:
  port: 8446
logging:
  file: /java/MHC_LOGS/pcm/pcm.log
info:
  component: PCM API
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    secure-port-enabled: false
    non-secure-port-enabled: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: https://localhost:8761/eureka/
# TODO: enable feign hystrix back when PHR API is refactored to a service that can be called by this API without OAuth2 token
feign.hystrix.enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pcm?autoReconnect=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    validation-query: select 1
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    time-between-eviction-runs-millis: 1800000
    num-tests-per-eviction-run: 3
    min-evictable-idle-time-millis: 1800000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: validate
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: consent2share@gmail.com
    password: fei@columbia
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  messages:
    basename: i18n/messages
security:
  basic:
    enabled: false
  oauth2:
    resource:
      jwt:
        keyValue:
                         -----BEGIN PUBLIC KEY-----
                         MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0m59l2u9iDnMbrXHfqkO
                         rn2dVQ3vfBJqcDuFUK03d+1PZGbVlNCqnkpIJ8syFppW8ljnWweP7+LiWpRoz0I7
                         fYb3d8TjhV86Y997Fl4DBrxgM6KTJOuE/uxnoDhZQ14LgOU2ckXjOzOdTsnGMKQB
                         LCl0vpcXBtFLMaSbpv1ozi8h7DJyVZ6EnFQZUWGdgTMhDrmqevfx95U/16c5WBDO
                         kqwIn7Glry9n9Suxygbf8g5AzpWcusZgDLIIZ7JTUldBb8qU2a0Dl4mvLZOn4wPo
                         jfj9Cw2QICsc5+Pwf21fP+hzf+1WSRHbnYv8uanRO0gZ8ekGaghM/2H6gqJbo2nI
                         JwIDAQAB
                         -----END PUBLIC KEY-----
      user-info-uri: https://localhost:8443/uaa/userinfo
    client:
      client-id: pcm
mhc:
  pcm:
    config:
      clinicaldata:
        maximumUploadFileSize: 10000000
        extensionsPermittedToUpload: xml,txt
      clamd:
        host: 172.20.139.101
        port: 3310
        connTimeOut: 90
      pid:
        domain:
          id: 1.3.6.1.4.1.21367.13.20.200
          type: ISO
        org: C2S Health
        prefix: C2S
      echosign:
        echoSignDocumentServiceEndpointAddress: https://secure.echosign.com/services/EchoSignDocumentService20
        echoSignApiKey: SBC5B7XK5A7Y5V
        esignaturePollingServicePollTaskFixedDelayInMilliseconds: 2000
      pls:
        api: https://localhost:8443/pls/providers
      pagination:
        itemsPerPage: 10
      activity:
        sql:
          path: activity/PatientActivityHistory.sql
      ssn:
        system: http://hl7.org/fhir/v2/0203
        oid: urn:oid:2.16.840.1.113883.4.1
        label: SSN
      npi:
        system: http://hl7.org/fhir/sid/us-npi
        oid: urn:oid:2.16.840.1.113883.4.6
        label: PRN
      pou:
        system: http://hl7.org/fhir/ValueSet/v3-PurposeOfUse
        oid: urn:oid:2.16.840.1.113883.1.11.20448
        label: PurposeOfUse
      fhir:
        serverUrl: https://localhost:8443/iexhub/services
        fhirClientSocketTimeoutInMs: 768000

  vss:
    config:
      conceptCodeListPageSize: 20
---
spring.profiles: ssl
server:
  port: 8446
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
eureka:
  instance:
    secure-port: ${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl
server:
  context-path: /pcm
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://pcm-db.mhc.com:3306/pcm?autoReconnect=true
mhc.pcm.config:
  pls.api: https://pls.mhc.com:8443/pls/providers
  clamd.host: clamd.mhc.com
security:
  oauth2:
    resource:
      user-info-uri: https://uaa.mhc.com:8443/uaa/userinfo
eureka:
  client:
    service-url:
      defaultZone: https://discovery-server.mhc.com:8761/eureka/
  instance:
    prefer-ip-address: true