# SSL is disabled by default for the PCM application.
#
# To enable SSL for PCM:
#   1) Activate the 'ssl' spring profile by passing in the following program argument:
#          a) --spring.profiles.active=ssl
#   2) Set the appropriate values for the 'server.ssl.key-store' and 'server.ssl.key-store-password' properties.
#          a) You can override/set these properties by setting them in an externalzied application.yml file.
#               EXAMPLE:
#                  server:
#                     ssl:
#                        key-store: /ssl_keystore.keystore
#                        key-store-password: changeit
#          b) Alternatively, you can pass the properties in using the following program arguments:
#                 i) --server.ssl.key-store=path-to-file/filename
#                ii) --server.ssl.key-store-password=your-keystore-password
info:
  component: PCM API
server:
  port: 8446
logging:
  # The 'file' property specifies the file which PCM will write its log events to.
  file: /java/C2S_LOGS/pcm/pcm.log
  # The 'path' property specifies the file system location where the 'FhirContractServiceImpl' class will log
  #   FHIR Contracts for debugging purposes. It is is ONLY for Fhir Contract logging, and it is not related to
  #   the pcm.log file in the 'file' property above. The 'path' property can point to any valid file system
  #   directory which PCM can access.
  path: /java/C2S_LOGS/pcm
security:
  oauth2:
    client:
      client-id: pcm
# TODO (#3): enable feign hystrix back when PHR API is refactored to a service that can be called by this API without OAuth2 token
feign.hystrix.enabled: false
spring:
  datasource:
  # PCM will utilize the database configured in this section
    url: jdbc:mysql://localhost:3306/pcm?autoReconnect=true
    # DO NOT USE THE FOLLOWING DEFAULT USERNAME OUTSIDE OF DEVELOPMENT ENVIRONMENTS!
    username: root
    # DO NOT USE THE FOLLOWING DEFAULT PASSWORD OUTSIDE OF DEVELOPMENT ENVIRONMENTS!
    password: admin
  mail:
  # PCM will use the e-mail server configured in this section to send e-mails
    # Please configure valid e-mail server below to connect to SMTP server
    # Configure host, port, username and password per environment
    host: mail_host
    port: 25
    protocol: smtp
    username: mail_username
    password: mail_password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: mail_host
  messages:
    basename: i18n/messages/messages
    encoding: UTF-8
c2s:
  pcm:
    clinicaldata:
      # Max allowed file size in bytes for clinical document files uploaded to PCM
      maximumUploadFileSize: 10000000
      # Comma separated list of permitted file extensions for clinical document files uploaded to PCM
      extensionsPermittedToUpload: xml,txt
    clamd:
      # Please configure valid server information below to connect to ClamAV server
      # Host name or IP address of server instance of ClamAV to use for virus scanning uploaded clinical document files
      host: localhost
      # Port number to connect to on host server instance of ClamAV to use for virus scanning uploaded clinical document files
      port: 3310
      # Time in seconds to wait before timing out when sending a clinical document file to ClamAV server.
      connTimeOut: 90
    pid:
      domain:
        # PCM's PID
        id: 1.3.6.1.4.1.21367.13.20.200
        system: https://bhits.github.io/consent2share/
        type: ISO
      org: C2S Health
      prefix: C2S
    pagination:
      itemsPerPage: 10
    activity:
      sql:
        path: activity/PatientActivityHistory.sql
    ssn:
      system: http://hl7.org/fhir/sid/us-ssn
      oid: urn:oid:2.16.840.1.113883.4.1
      label: SSN
    npi:
      system: http://hl7.org/fhir/sid/us-npi
      oid: urn:oid:2.16.840.1.113883.4.6
      label: PRN
    pou:
      system: http://hl7.org/fhir/v3/ActReason
      oid: urn:oid:2.16.840.1.113883.1.11.20448
      label: PurposeOfUse
    consentType:
      system: http://hl7.org/fhir/ValueSet/v3-ActConsentType
      oid: urn:oid:2.16.840.1.113883.1.11.19897
      label: information disclosure
      code: IDSCL
    keepExcludeList: false
    hie-connection:
      fhir:
        enabled: false
        # If SSL is turned on in the IExHub application, you must change/override the 'serverUrl' property below
        #   to use 'https://' instead of 'http://'. You must also change/override the port number in the URL.
        serverUrl: http://localhost:8080/iexhub/services
        clientSocketTimeoutInMs: 768000
    pdfConfigs:
      - type: consent-pdf
        title: Consent to Share My Health Information
        pdFont: TIMES_ROMAN
        pdfPageSize: LETTER
      - type: consent-revocation-pdf
        title: Revocation of Consent to Share My Health Information
        pdFont: TIMES_ROMAN
        pdfPageSize: LETTER
  vss:
    conceptCodeListPageSize: 20
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /pcm
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://${C2S_DB_HOST:pcm-db.c2s.com}:${C2S_DB_PORT:3306}/pcm?autoReconnect=true
security:
  oauth2:
    resource:
      # If SSL is turned on in the UAA application, you must change/override the 'user-info-uri' property below
      #   to use 'https://' instead of 'http://'. You must also change/override the port number in the URL.
      user-info-uri: http://uaa.c2s.com:8080/uaa/userinfo
c2s:
  pcm:
    clamd:
      host: clamd.c2s.com
    hie-connection:
      fhir:
        serverUrl: http://iexhub.c2s.com:8080/iexhub/services
